spring.config.activate.on-profile=opaque
spring.security.oauth2.resourceserver.opaquetoken.introspection-uri=${OAUTH_INTROSPECTION_URI:http://localhost:8180/realms/auth-demo/protocol/openid-connect/token/introspect}
spring.security.oauth2.resourceserver.opaquetoken.client-id=${OAUTH_INTROSPECTION_CLIENT_ID:auth-demo-resource-server}
spring.security.oauth2.resourceserver.opaquetoken.client-secret=${OAUTH_INTROSPECTION_CLIENT_SECRET:}
