spring.config.activate.on-profile=ldap
auth-demo.ldap.url=${LDAP_URL:ldap://localhost:1389}
auth-demo.ldap.base=${LDAP_BASE:dc=example,dc=org}
auth-demo.ldap.manager-dn=${LDAP_MANAGER_DN:cn=admin,dc=example,dc=org}
auth-demo.ldap.manager-password=${LDAP_MANAGER_PASSWORD:admin}
auth-demo.ldap.user-dn-pattern=uid={0},ou=people
auth-demo.ldap.group-search-base=ou=groups
