spring.config.activate.on-profile=mtls
server.ssl.enabled=true
server.ssl.key-store=${MTLS_SERVER_KEYSTORE:classpath:certs/server.p12}
server.ssl.key-store-password=${MTLS_SERVER_KEYSTORE_PASSWORD:changeit}
server.ssl.key-store-type=PKCS12
server.ssl.trust-store=${MTLS_TRUSTSTORE:classpath:certs/truststore.p12}
server.ssl.trust-store-password=${MTLS_TRUSTSTORE_PASSWORD:changeit}
server.ssl.client-auth=need
